package com.inventory.core.model.enumconstant;

public enum Permission {
	SERVICE_CREATE , SERVICE_VIEW , SERVICE_UPDATE , SERVICE_DELETE , 
	PRODUCT_CREATE , PRODUCT_VIEW , PRODUCT_UPDATE , PRODUCT_DELETE , 
	SALES_ORDER_CREATE , SALES_ORDER_VIEW , SALES_ORDER_UPDATE , SALES_ORDER_DELETE , 
	INVOICE_CREATE , INVOICE_VIEW , INVOICE_UPDATE , INVOICE_DELETE , 
	PURCHASE_ORDER_CREATE , PURCHASE_ORDER_VIEW , PURCHASE_ORDER_UPDATE , PURCHASE_ORDER_DELETE , 
	BILL_CREATE , BILL_VIEW , BILL_UPDATE , BILL_DELETE , 
	USER_CREATE , USER_VIEW , USER_UPDATE , USER_DELETE , 
	REPORT_CREATE , REPORT_VIEW , REPORT_UPDATE , REPORT_DELETE , 
	SUPPLIER_CREATE , SUPPLIER_VIEW , SUPPLIER_UPDATE , SUPPLIER_DELETE,
	ITEM_CREATE, ITEM_VIEW , ITEM_UPDATE , ITEM_DELETE,
	CATEGORY_CREATE , CATEGORY_VIEW, CATEGORY_UPDATE, CATEGORY_DELETE,
	SUBCATEGORY_CREATE , SUBCATEGORY_VIEW, SUBCATEGORY_UPDATE, SUBCATEGORY_DELETE,
	TAG_CREATE , TAG_VIEW, TAG_UPDATE, TAG_DELETE,
	UNIT_CREATE , UNIT_VIEW, UNIT_UPDATE, UNIT_DELETE,
	STORE_CREATE , STORE_VIEW, STORE_UPDATE, STORE_DELETE
}
