package com.inventory.core.model.enumconstant;

public enum Permission {

	CATEGORY_CREATE , CATEGORY_VIEW, CATEGORY_UPDATE, CATEGORY_DELETE,

	SUBCATEGORY_CREATE , SUBCATEGORY_VIEW, SUBCATEGORY_UPDATE, SUBCATEGORY_DELETE,

	TAG_CREATE , TAG_VIEW, TAG_UPDATE, TAG_DELETE,

	UNIT_CREATE , UNIT_VIEW, UNIT_UPDATE, UNIT_DELETE,

	PRODUCT_CREATE , PRODUCT_VIEW , PRODUCT_UPDATE , PRODUCT_DELETE ,

	ITEM_CREATE, ITEM_VIEW , ITEM_UPDATE , ITEM_DELETE,

	CLIENT_CREATE , CLIENT_VIEW , CLIENT_UPDATE , CLIENT_DELETE,

	SALES_ORDER_CREATE , SALES_ORDER_VIEW , SALES_ORDER_UPDATE , SALES_ORDER_DELETE ,

	PURCHASE_ORDER_CREATE , PURCHASE_ORDER_VIEW , PURCHASE_ORDER_UPDATE , PURCHASE_ORDER_DELETE ,

	INVOICE_CREATE , INVOICE_VIEW , INVOICE_UPDATE , INVOICE_DELETE ,

	PAYMENT_CREATE, PAYMENT_VIEW , PAYMENT_UPDATE , PAYMENT_DELETE ,

	SALES_ORDER_RETURN_CREATE , SALES_ORDER_RETURN_VIEW , SALES_ORDER_RETURN_UPDATE , SALES_ORDER_RETURN_DELETE ,

	PURCHASE_ORDER_RETURN_CREATE , PURCHASE_ORDER_RETURN_VIEW , PURCHASE_ORDER_RETURN_UPDATE , PURCHASE_ORDER_RETURN_DELETE ,

	REPORT_CREATE , REPORT_VIEW , REPORT_UPDATE , REPORT_DELETE ,

}
